### ISSUE TITLE
Local application 'OmniGraffle 5.app' not found

### ISSUE THREAD

**Issue by jhamrick** [fikovnik/omnigraffle-export#16]
When I try to run `omnigraffle_export`, it (correctly) fails to find OmniGraffle 5, which does not exist:

```bash
$ python -c "import appscript; print appscript.app('OmniGraffle 5')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appscript-1.0.1-py2.7-macosx-10.8-x86_64.egg/appscript/reference.py", line 801, in __call__
    return self._appclass(*args, **kargs)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appscript-1.0.1-py2.7-macosx-10.8-x86_64.egg/appscript/reference.py", line 736, in __init__
    constructor, identifier = 'path', aem.findapp.byname(name)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appscript-1.0.1-py2.7-macosx-10.8-x86_64.egg/aem/findapp.py", line 51, in byname
    name = _findapp(name + '.app')
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/appscript-1.0.1-py2.7-macosx-10.8-x86_64.egg/aem/findapp.py", line 18, in _findapp
    raise ApplicationNotFoundError(name or id or creator)
aem.findapp.ApplicationNotFoundError: Local application 'OmniGraffle 5.app' not found.
```

Instead, I have 'OmniGraffle Professional 5', but `omnigraffle.py` looks exclusively for 'OmniGraffle 5'. I've created a patch which first tries to find OmniGraffle 5, and if that fails, tries to find OmniGraffle Professional 5. You can find it here: https://gist.github.com/jhamrick/5392294

Thanks for this great tool!

**Comment by fikovnik** [comment]
This should be fixed already from 1.6.
