### ISSUE TITLE
OmniGraffle 6 not supported. :(

### ISSUE THREAD

**Issue by drusellers** [fikovnik/omnigraffle-export#23]
I have no idea what has changed between 5 and 6 - but i do know the application name has changed to OmniGraffle.app.

**Comment by fikovnik** [comment]
There were some changes - sandboxing and name changes. Could you please check the latest version - 1.7.

**Comment by drusellers** [comment]
```
git checkout develop
sudo python setup.py install
$ omnigraffle-export -f png ~/Dropbox/MAG/the-line.graffle ./bob/
Traceback (most recent call last):
  File "/usr/local/bin/omnigraffle-export", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyobjc-framework-Social==3.0.4
```

**Comment by fikovnik** [comment]
Can you try in an empty virtual environment?

```
$ source /usr/local/bin/virtualenvwrapper.sh
$ mkvirtualenv test
$ python setup.py install
$ omnigraffle-export -f png ~/Dropbox/MAG/the-line.graffle ./bob/
$ python setup.py test # optinaly
```

There seems to be some dependencies problems and this will help us to debug find out where.

**Comment by drusellers** [comment]
that blew up in a HUGE way. I also had to sudo the install. I'm guessing i have something wonky going on. hmmm.

**Comment by fikovnik** [comment]
I guess, but it is weird as this should create a completely clean environment.

**Comment by drusellers** [comment]
I'm using system python. So I can try a homebrew install of python?

**Comment by fikovnik** [comment]
You could try, but it should work with the system one. I just tried that using a new virtual environment:

```
$ mkvirtualenv -p /usr/bin/python2.7 omnigraffle-sysp27
...
(omnigraffle-sysp27)$ git clone https://github.com/fikovnik/omnigraffle-export.git
...
(omnigraffle-sysp27)$ cd omnigraffle-export/
(omnigraffle-sysp27)$ python setup.py install
...
(omnigraffle-sysp27)$ omnigraffle-export -f png tests/test_data/basic/test.graffle .
(omnigraffle-sysp27)$ ls *.png
Canvas 1.png  Canvas 2.png
```

These are the state of pip packages:

```sh
(omnigraffle-sysp27)$ pip freeze
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
altgraph==0.12
appscript==1.0.1
macholib==1.7
modulegraph==0.12
omnigraffle-export==1.7.1
py2app==0.9
pyobjc==3.0.4
pyobjc-core==3.0.4
pyobjc-framework-Accounts==3.0.4
pyobjc-framework-AddressBook==3.0.4
pyobjc-framework-AppleScriptKit==3.0.4
pyobjc-framework-AppleScriptObjC==3.0.4
pyobjc-framework-Automator==3.0.4
pyobjc-framework-CalendarStore==3.0.4
pyobjc-framework-CFNetwork==3.0.4
pyobjc-framework-Cocoa==3.0.4
pyobjc-framework-Collaboration==3.0.4
pyobjc-framework-CoreData==3.0.4
pyobjc-framework-CoreLocation==3.0.4
pyobjc-framework-CoreText==3.0.4
pyobjc-framework-CoreWLAN==3.0.4
pyobjc-framework-DictionaryServices==3.0.4
pyobjc-framework-DiskArbitration==3.0.4
pyobjc-framework-EventKit==3.0.4
pyobjc-framework-ExceptionHandling==3.0.4
pyobjc-framework-FSEvents==3.0.4
pyobjc-framework-InputMethodKit==3.0.4
pyobjc-framework-InstallerPlugins==3.0.4
pyobjc-framework-InstantMessage==3.0.4
pyobjc-framework-LatentSemanticMapping==3.0.4
pyobjc-framework-LaunchServices==3.0.4
pyobjc-framework-PreferencePanes==3.0.4
pyobjc-framework-PubSub==3.0.4
pyobjc-framework-QTKit==3.0.4
pyobjc-framework-Quartz==3.0.4
pyobjc-framework-ScreenSaver==3.0.4
pyobjc-framework-ScriptingBridge==3.0.4
pyobjc-framework-SearchKit==3.0.4
pyobjc-framework-ServiceManagement==3.0.4
pyobjc-framework-Social==3.0.4
pyobjc-framework-StoreKit==3.0.4
pyobjc-framework-SyncServices==3.0.4
pyobjc-framework-SystemConfiguration==3.0.4
pyobjc-framework-WebKit==3.0.4
```

**Comment by Razer6** [comment]
I have the same issue. I installed via virtualenv and get the following error message when starting the tool:

```
(omni)/tmp⚡ ⇒ omnigraffle-export 
Traceback (most recent call last):
  File "/usr/local/bin/omnigraffle-export", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyobjc-framework-Social==3.0.4
```

Here is my list of dependencies installed in the virtualenv:

```
(omni)/tmp⚡ ⇒ pip freeze
altgraph==0.12
appscript==1.0.1
macholib==1.7
modulegraph==0.12.1
omnigraffle-export==1.7.1
py2app==0.9
pyobjc==3.0.4
pyobjc-core==3.0.4
pyobjc-framework-Accounts==3.0.4
pyobjc-framework-AddressBook==3.0.4
pyobjc-framework-AppleScriptKit==3.0.4
pyobjc-framework-AppleScriptObjC==3.0.4
pyobjc-framework-Automator==3.0.4
pyobjc-framework-CalendarStore==3.0.4
pyobjc-framework-CFNetwork==3.0.4
pyobjc-framework-Cocoa==3.0.4
pyobjc-framework-Collaboration==3.0.4
pyobjc-framework-CoreData==3.0.4
pyobjc-framework-CoreLocation==3.0.4
pyobjc-framework-CoreText==3.0.4
pyobjc-framework-CoreWLAN==3.0.4
pyobjc-framework-DictionaryServices==3.0.4
pyobjc-framework-DiskArbitration==3.0.4
pyobjc-framework-EventKit==3.0.4
pyobjc-framework-ExceptionHandling==3.0.4
pyobjc-framework-FSEvents==3.0.4
pyobjc-framework-InputMethodKit==3.0.4
pyobjc-framework-InstallerPlugins==3.0.4
pyobjc-framework-InstantMessage==3.0.4
pyobjc-framework-LatentSemanticMapping==3.0.4
pyobjc-framework-LaunchServices==3.0.4
pyobjc-framework-PreferencePanes==3.0.4
pyobjc-framework-PubSub==3.0.4
pyobjc-framework-QTKit==3.0.4
pyobjc-framework-Quartz==3.0.4
pyobjc-framework-ScreLenSaver==3.0.4
pyobjc-framework-ScriptingBridge==3.0.4
pyobjc-framework-SearchKit==3.0.4
pyobjc-framework-ServiceManagement==3.0.4
pyobjc-framework-Social==3.0.4
pyobjc-framework-StoreKit==3.0.4
pyobjc-framework-SyncServices==3.0.4
pyobjc-framework-SystemConfiguration==3.0.4
pyobjc-framework-WebKit==3.0.4
wheel==0.24.0
```

**Comment by CaliLuke** [comment]
I'm seeing the exact same issue. Is there any plans to address it?
