### ISSUE TITLE
Will this work with an App Store purchased version?

### ISSUE THREAD

**Issue by drusellers** [fikovnik/omnigraffle-export#24]
There may be some sandboxing going on as i am getting permission errors.

-d

**Comment by drusellers** [comment]
I found this : http://forums.omnigroup.com/showthread.php?t=31062

which lead to this

https://developer.apple.com/library/mac/releasenotes/AppleScript/RN-AppleScript/RN-10_8/RN-10_8.html

**Comment by fikovnik** [comment]
Could you try the 1.7 version to see if you see the same problem?

**Comment by fikovnik** [comment]
It would not solve it - today  created a 1.7.1 that has this (not a very good one) fix: 53dddfe8f9c5c034ae6ba5676aed31a16a76a0a5

**Comment by drusellers** [comment]
```
git checkout develop
sudo python setup.py install

omnigraffle-export -f png ~/Dropbox/MAG/the-line.graffle bob
Traceback (most recent call last):
  File "/usr/local/bin/omnigraffle-export", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyobjc-framework-Social==3.0.4
```

**Comment by fikovnik** [comment]
It is difficult for me to reproduce, I don't get the same error. What you could try is to install this package to see if the problem goes away https://pypi.python.org/pypi/pyobjc-framework-Social either manually or adding it to the `setup.py`

**Comment by cmbuckley** [comment]
There is a similar issue in OmniGraffle 7:

<img width="417" alt="screen shot 2017-05-16 at 12 56 35" src="https://cloud.githubusercontent.com/assets/80938/26104745/239a86d4-3a37-11e7-88d0-becfe8ae44ed.png">

This is seen with or without the above fix — e.g. experience is the same on 1.7 and current master.
